version: '3.7'
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DB: lireddit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
